### ISSUE TITLE
Add `pre-exit` tests in `tests/` folder

### ISSUE THREAD

**Issue by Delta456** [LambdaTest/lambdatest-buildkite-plugin#4]
There is a test for `pre-command` in `tests` folder. The `hooks` folder need consists of both `pre-command` and `pre-exit`. The tests for `pre-exit` are missing.

**Comment by swayam0322** [comment]
@navin772 I wanna work on this issue

**Comment by navin772** [comment]
@swayam0322 any updates on this?

**Comment by swayam0322** [comment]
@navin772 Please review the PR
