### ISSUE TITLE
update buildkit plugin tester to latest version

### ISSUE THREAD

**Issue by Delta456** [LambdaTest/lambdatest-buildkite-plugin#5]
The current  `buildkite/plugin-tester` version is `v4.0.0` as defined in `docker-compose.yml` of the repo. 

The latest version is `v4.1.1` as per the release at https://github.com/buildkite-plugins/buildkite-plugin-tester/releases/tag/v4.1.1. 

We need to update the plugin tester and make the repo work with the latest version

**Comment by Delta456** [comment]
@Yash-sudo-web please go ahead!

**Comment by Yash-sudo-web** [comment]
@Delta456 after updating the version and running the docker compose file, its giving this
{ total: 3, pass: 1, fail: 1, skip: 1 } followed with some logs
is there a discord server or slack community we can connect on?

**Comment by Delta456** [comment]
> @Delta456 after updating the version and running the docker compose file, its giving this
> { total: 3, pass: 1, fail: 1, skip: 1 } followed with some logs
> is there a discord server or slack community we can connect on?

Yes, there is a discord server. This is the invite link discord.gg/Q5SnqxqV
