### ISSUE TITLE
add GitHub actions

### ISSUE THREAD

**Issue by Delta456** [LambdaTest/lambdatest-buildkite-plugin#6]
Add GitHub Actions for the project which runs everything inside the `.ci/` folder and makes sure it passes on every commit.

Refer to the [documentation](https://docs.github.com/en/actions) for in-depth tutorial of GitHub Actions.

**Comment by s-vamshi** [comment]
Hey @navin772 @Delta456 i would like to work on this issue, can you please assign this to me?

**Comment by navin772** [comment]
Thanks for taking this up @s-vamshi, assigning you this issue!

**Comment by pearguacamole** [comment]
Hi, I have created a workflow for GitHub actions which runs all the scripts inside `.ci/` folder, and the run fails in case the test/lint script fails. The pull request with the changes should close this issue.
